// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt3H_voYbPZmWwzqzIBViByjC_kgE6RUU',
    appId: '1:257562578183:web:5c49009be67093af2749a2',
    messagingSenderId: '257562578183',
    projectId: 'agriaiassistant',
    authDomain: 'agriaiassistant.firebaseapp.com',
    databaseURL: 'https://agriaiassistant-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agriaiassistant.firebasestorage.app',
    measurementId: 'G-4PJ90HGW81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVF7vHVI1SAoeZPorOk8vT8LxasMZFOT4',
    appId: '1:257562578183:android:c9dd1aa7b37f327b2749a2',
    messagingSenderId: '257562578183',
    projectId: 'agriaiassistant',
    databaseURL: 'https://agriaiassistant-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agriaiassistant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCslfLYloGJUnk0QG1vF5GClyHPCpesQK4',
    appId: '1:257562578183:ios:e5424b63df042ec32749a2',
    messagingSenderId: '257562578183',
    projectId: 'agriaiassistant',
    databaseURL: 'https://agriaiassistant-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agriaiassistant.firebasestorage.app',
    iosBundleId: 'com.example.agriAiAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCslfLYloGJUnk0QG1vF5GClyHPCpesQK4',
    appId: '1:257562578183:ios:e5424b63df042ec32749a2',
    messagingSenderId: '257562578183',
    projectId: 'agriaiassistant',
    databaseURL: 'https://agriaiassistant-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agriaiassistant.firebasestorage.app',
    iosBundleId: 'com.example.agriAiAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt3H_voYbPZmWwzqzIBViByjC_kgE6RUU',
    appId: '1:257562578183:web:acfea6daa868558d2749a2',
    messagingSenderId: '257562578183',
    projectId: 'agriaiassistant',
    authDomain: 'agriaiassistant.firebaseapp.com',
    databaseURL: 'https://agriaiassistant-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agriaiassistant.firebasestorage.app',
    measurementId: 'G-FT9HWBB5JV',
  );

}